import { EditorialPage } from "@/components/EditorialPage";
import { resolveLocale } from "@/lib/locale";
export default async function Page({params}:{params:Promise<{locale:string}>}){
 const locale=resolveLocale((await params).locale); const ro=locale==='ro';
 return <EditorialPage locale={locale} kicker="KINDNESS · COMMUNITY" title="Gentleness should be ordinary." intro={ro?"Kindness la Pocket Goat nu este campanie, estetică roz sau promisiune terapeutică. Este hospitality atent: felul în care vorbește personalul, cum este respectată liniștea și cum sunt gândite gesturile mici.":"Kindness at Pocket Goat is not a campaign, pink aesthetics or a therapeutic promise. It is attentive hospitality: how staff speak, how quiet is respected and how small gestures are designed."} features={[
 {title:"Hard Day Tea",meta:"NO EXPLANATION REQUIRED",text:ro?"Un gest simplu și discret pentru cineva care spune că a avut o zi grea. Fără dovadă, fără poveste obligatorie, fără marketing agresiv.":"A simple, discreet gesture for someone who says they had a hard day. No proof, no required story, no aggressive marketing."},
 {title:"Leave a Story / Take a Story",meta:"RECIPROCITY",text:ro?"Un schimb de povești, recomandări sau fragmente care lasă urme mici între oameni care nu trebuie să se cunoască.":"An exchange of stories, recommendations or fragments that leaves small traces between people who do not need to know each other."},
 {title:"The Things We Leave Behind",meta:"CURATED · MODERATED",text:ro?"Scrisori sau mesaje anonime publicate doar cu o moderare atentă și reguli clare, ca arhivă umană, nu ca zid de traumă.":"Anonymous letters or notes published only with careful moderation and clear rules, as a human archive rather than a wall of trauma."},
 {title:"Quiet Company",meta:"NO SOCIAL OBLIGATION",text:ro?"Singur nu înseamnă disponibil pentru conversație. Tăcerea și limitele oamenilor sunt parte din design, nu obstacole pentru business.":"Alone does not mean available for conversation. People’s quiet and boundaries are part of the design, not obstacles to business."}
 ]}>
 <section id="bring-an-idea" className="idea-section section-forest"><p className="kicker">POCKET GOAT COMMUNITY</p><h2>You bring the idea.<br/>We provide the table.</h2><p>{ro?"Ai o idee culturală potrivită cu cărțile, cunoașterea, istoria, limbile, arta sau viața orașului? O poți propune. Pocket Goat decide dacă se potrivește, în ce formă și când.":"Have a cultural idea that belongs with books, knowledge, history, languages, art or city life? You can propose it. Pocket Goat decides whether it fits, in what form and when."}</p><div className="idea-rules"><span>{ro?"Curatoriat, nu open booking":"Curated, not open booking"}</span><span>{ro?"Cultural, nu comercial":"Cultural, not commercial"}</span><span>{ro?"O parte mică din program":"A smaller share of the programme"}</span></div></section>
 </EditorialPage>
}
